/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package group1.views;

import java.sql.Date;
import java.util.List;

import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;

import group1.entity.HoaDon;

/**
 *
 * @author numpa
 */
public class DoanhThuJDialog extends javax.swing.JDialog {

        /**
         * Creates new form DoanhThuJDialog
         */
        public DoanhThuJDialog(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
                setLocationRelativeTo(null);
        }

        // void fillTableByDay() {
        // DefaultTableModel model = (DefaultTableModel) tbl_day.getModel();
        // model.setRowCount(0);
        // try {
        // Date date = new Date(lbl_date.getDate().getTime());
        // List<HoaDon> list = TKdao.selectByDay(date);
        // int i = 1;
        // for (HoaDon hd : list) {
        // Object[] row = {
        // i++,
        // hd.getMaHD(),
        // hd.getNgayTao(),
        // // hd.TongTien(),
        // hd.getMaNV()
        // };
        // model.addRow(row);
        // }
        // } catch (Exception e) {
        // e.printStackTrace();
        // }
        // // }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jInternalFrame1 = new javax.swing.JInternalFrame();
                jPanel1 = new javax.swing.JPanel();
                lbl_title = new javax.swing.JLabel();
                jTabbedPane2 = new javax.swing.JTabbedPane();
                Day = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tbl_day = new javax.swing.JTable();
                lbl_date = new com.toedter.calendar.JDateChooser();
                btn_go = new javax.swing.JButton();
                Month = new javax.swing.JPanel();
                jScrollPane4 = new javax.swing.JScrollPane();
                tbl_month = new javax.swing.JTable();
                Year = new javax.swing.JPanel();
                jScrollPane5 = new javax.swing.JScrollPane();
                tbl_year = new javax.swing.JTable();

                jInternalFrame1.setVisible(true);

                javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(
                                jInternalFrame1.getContentPane());
                jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
                jInternalFrame1Layout.setHorizontalGroup(
                                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));
                jInternalFrame1Layout.setVerticalGroup(
                                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setAutoRequestFocus(false);
                setBackground(new java.awt.Color(132, 35, 60));

                jPanel1.setBackground(new java.awt.Color(132, 35, 60));

                lbl_title.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
                lbl_title.setForeground(new java.awt.Color(235, 202, 188));
                lbl_title.setText("DOANH THU");

                jTabbedPane2.setForeground(new java.awt.Color(242, 240, 235));

                Day.setBackground(new java.awt.Color(132, 35, 60));

                tbl_day.setBackground(new java.awt.Color(0, 98, 65));
                tbl_day.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null }
                                },
                                new String[] {
                                                "STT", "Mã HD", "Ngày Tạo", "Tổng Tiền", "Người Tạo"
                                }));
                jScrollPane1.setViewportView(tbl_day);

                btn_go.setText("Truy Vấn");
                btn_go.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_goActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout DayLayout = new javax.swing.GroupLayout(Day);
                Day.setLayout(DayLayout);
                DayLayout.setHorizontalGroup(
                                DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1007,
                                                                Short.MAX_VALUE)
                                                .addGroup(DayLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(btn_go)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(lbl_date,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                298,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
                DayLayout.setVerticalGroup(
                                DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DayLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(DayLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lbl_date,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btn_go))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                561,
                                                                                Short.MAX_VALUE)));

                jTabbedPane2.addTab("Ngày", Day);

                tbl_month.setBackground(new java.awt.Color(0, 98, 65));
                tbl_month.setForeground(new java.awt.Color(242, 240, 235));
                tbl_month.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null }
                                },
                                new String[] {
                                                "STT", "Mã HD", "Ngày Tạo", "Tổng Tiền", "Người Tạo"
                                }));
                jScrollPane4.setViewportView(tbl_month);

                javax.swing.GroupLayout MonthLayout = new javax.swing.GroupLayout(Month);
                Month.setLayout(MonthLayout);
                MonthLayout.setHorizontalGroup(
                                MonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1007,
                                                                Short.MAX_VALUE));
                MonthLayout.setVerticalGroup(
                                MonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 600,
                                                                Short.MAX_VALUE));

                jTabbedPane2.addTab("Tháng", Month);

                tbl_year.setBackground(new java.awt.Color(0, 98, 65));
                tbl_year.setForeground(new java.awt.Color(242, 240, 235));
                tbl_year.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null }
                                },
                                new String[] {
                                                "STT", "Mã HD", "Ngày Tạo", "Tổng Tiền", "Người Tạo"
                                }));
                jScrollPane5.setViewportView(tbl_year);

                javax.swing.GroupLayout YearLayout = new javax.swing.GroupLayout(Year);
                Year.setLayout(YearLayout);
                YearLayout.setHorizontalGroup(
                                YearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1007,
                                                                Short.MAX_VALUE));
                YearLayout.setVerticalGroup(
                                YearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 600,
                                                                Short.MAX_VALUE));

                jTabbedPane2.addTab("Năm", Year);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTabbedPane2)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(384, 384, 384)
                                                                .addComponent(lbl_title)
                                                                .addGap(0, 0, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(lbl_title)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jTabbedPane2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                631,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btn_goActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_goActionPerformed
                // TODO add your handling code here:
                // fillTableByDay();
        }// GEN-LAST:event_btn_goActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(DoanhThuJDialog.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(DoanhThuJDialog.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(DoanhThuJDialog.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(DoanhThuJDialog.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                DoanhThuJDialog dialog = new DoanhThuJDialog(new javax.swing.JFrame(), true);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel Day;
        private javax.swing.JPanel Month;
        private javax.swing.JPanel Year;
        private javax.swing.JButton btn_go;
        private javax.swing.JInternalFrame jInternalFrame1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JTabbedPane jTabbedPane2;
        private com.toedter.calendar.JDateChooser lbl_date;
        private javax.swing.JLabel lbl_title;
        private javax.swing.JTable tbl_day;
        private javax.swing.JTable tbl_month;
        private javax.swing.JTable tbl_year;
        // End of variables declaration//GEN-END:variables
}
